import { createElement } from 'lwc';
import JestDemo from 'c/jestDemo';

describe('c-jest-demo', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-jest-demo', {
            is: JestDemo
        });

        // Act
        document.body.appendChild(element);

        // Assert
         const p1 = element.shadowRoot.querySelector('p');
         const inputElement = element.shadowRoot.querySelector('lightning-input');
         inputElement.value = 'show';
         inputElement.dispatchEvent(new CustomEvent('change'));
         return Promise.resolve().then(() => {
            expect(p1).toBeVisible();
          });

    });
});